import { getDistinctWays, getJoltDifferenceResult } from "./day10";

describe("day10", () => {
  describe("getJoltDifferenceResult", () => {
    test("should return 35", () => {
      expect(
        getJoltDifferenceResult(`
          16
          10
          15
          5
          1
          11
          7
          19
          6
          12
          4
      `)
      ).toEqual(35);
    });
    test("should return 220", () => {
      expect(
        getJoltDifferenceResult(`
          28
          33
          18
          42
          31
          14
          46
          20
          48
          47
          24
          23
          49
          45
          19
          38
          39
          11
          1
          32
          25
          35
          8
          17
          7
          9
          4
          2
          34
          10
          3
        `)
      ).toEqual(220);
    });
  });
  describe("getDistinctWays", () => {
    test("should return 8", () => {
      expect(
        getDistinctWays(`
          16
          10
          15
          5
          1
          11
          7
          19
          6
          12
          4
      `)
      ).toEqual(8);
    });
    test("should return 19208", () => {
      expect(
        getDistinctWays(`
          28
          33
          18
          42
          31
          14
          46
          20
          48
          47
          24
          23
          49
          45
          19
          38
          39
          11
          1
          32
          25
          35
          8
          17
          7
          9
          4
          2
          34
          10
          3
        `)
      ).toEqual(19208);
    });
  });
});
